
import { Toaster } from "@repo/ui/components/ui/sonner";
import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Footer } from "@repo/ui/components/footer/Footer";
import MarketplaceNavBarClient from "../components/MarketplaceNavBarClient";
import ReactQueryProvider from "@repo/ui/providers/QueryClientProvider";
import type { FooterSection } from '@repo/ui/components/footer/Footer';
import { Inter } from "next/font/google";

import type { ProfileData } from "@repo/ui/components/navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "marketplace",
  description: "Generated by create turbo",
};

const marketplaceFooterSections: FooterSection[] = [
  {
    title: "Home",
    links: [
      { label: "My favorites", href: "/marketplace/my-favorites" },
      { label: "Recents", href: "/marketplace/recents" },
    ],
  },
  {
    title: "Buy & Sell",
    links: [
      { label: "Buy Vehicle", href: "/marketplace/buy-vehicle" },
      { label: "Sell Vehicle", href: "/marketplace/sell-vehicle" },
    ],
  },
  { title: "Hiring", links: [{ label: "Jobs", href: "/marketplace/jobs" }] },
  {
    title: "Company",
    links: [
      { label: "Terms & Conditions", href: "/legal/terms" },
      { label: "Privacy Policy", href: "/legal/privacy" },
      { label: "Legal Terms", href: "/legal/general-terms" },
      { label: "Marketplace Blog", href: "/marketplace/blog" },
    ],
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {


  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ReactQueryProvider>
          <MarketplaceNavBarClient />
          <main className=" bg-[#FAFAFB]">{children}</main>
          <Footer
            footerSections={marketplaceFooterSections}
            companyName="Marketplace Solutions Inc."
          />
        </ReactQueryProvider>
        <Toaster
          toastOptions={{
            classNames: {
              default:
                "bg-white text-slate-900 dark:bg-slate-900 dark:text-slate-50 z-50 p-4 shadow-lg backdrop-blur-md ",
              success:
                "bg-green-500 text-white z-50 p-4 shadow-lg backdrop-blur-md ",
              error:
                "bg-red-500 text-white z-50 p-4 shadow-lg backdrop-blur-md ",
              loading:
                "bg-blue-500 text-white z-50 p-4 shadow-lg backdrop-blur-md ",
            },
          }}
        />
      </body>
    </html>
  );
}
