import { Footer } from "@repo/ui/components/footer/Footer";
import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { FooterSection, FooterLinkItem } from "@repo/ui/components/footer/Footer";
import DriverJobsNavBarClient from "./components/DriverJobsNavBarClient";
import ReactQueryProvider from "@repo/ui/providers/QueryClientProvider";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "driverjobs",
  description: "Generated by create turbo",
};

const driverJobsFooterSections: FooterSection[] = [
  {
    title: "Home",
    links: [
      { label: "My favorites", href: "/marketplace/my-favorites" },
      { label: "Recents", href: "/marketplace/recents" },
    ],
  },
  {
    title: "Buy & Sell",
    links: [
      { label: "Buy Vehicle", href: "/marketplace/buy-vehicle" },
      { label: "Sell Vehicle", href: "/marketplace/sell-vehicle" },
    ],
  },
  { title: "Hiring", links: [{ label: "Jobs", href: "/marketplace/jobs" }] },
  { title: "Insurance", links: [{ label: "Buy Insurance", href: "/marketplace/insurance" }] },
  {
    title: "Company",
    links: [
      { label: "Terms & Conditions", href: "/legal/terms" },
      { label: "Privacy Policy", href: "/legal/privacy" },
      { label: "Legal Terms", href: "/legal/general-terms" },
      { label: "Marketplace Blog", href: "/marketplace/blog" },
    ],
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <DriverJobsNavBarClient />
          <main className="pb-16 md:pb-0">
            {children}
          </main>
          <Footer
            footerSections={driverJobsFooterSections} // Pass the data as a prop
            companyName="Driver Job Connect"
          />
        </ReactQueryProvider>
        <Toaster
          // position="bottom-center"
          toastOptions={{
            classNames: {
              default:
                "bg-white text-slate-900 dark:bg-slate-900 dark:text-slate-50 z-50 p-4 shadow-lg backdrop-blur-md ",
              success:
                "bg-green-500 text-white z-50 p-4 shadow-lg backdrop-blur-md ",
              error:
                "bg-red-500 text-white z-50 p-4 shadow-lg backdrop-blur-md ",
              loading:
                "bg-blue-500 text-white z-50 p-4 shadow-lg backdrop-blur-md ",
            },
          }}
        />
      </body>
    </html>
  );
}
